_wandb:
    value:
        cli_version: 0.26.0
        e:
            qvb8z46cg7xsgo710fhvnw57dxy9ojn5:
                args:
                    - --hf_dataset
                    - chirunder/MixAtis_for_DecoderOnly
                    - --model_name_or_path
                    - meta-llama/Llama-3.2-1B
                    - --output_dir
                    - ./out/atis_run1
                    - --do_train
                    - --do_eval
                    - --use_soft_slot
                    - --use_gc
                    - --use_amp
                    - --use_wandb
                    - --wandb_project
                    - bislu-pabee
                    - --wandb_run_name
                    - llama1b_atis_tau0.05_p3
                    - --bislu_aux_loss_coef
                    - "0.3"
                    - --ee_patience
                    - "3"
                    - --tau_intent
                    - "0.05"
                    - --use_freq_exit
                codePath: intent.py
                codePathLocal: intent.py
                cpu_count: 40
                cpu_count_logical: 80
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "928614051840"
                        used: "904209342464"
                email: tahir2011.iiui@gmail.com
                executable: /home/tahir/miniconda3/bin/python
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-538ae2e1-87d3-fdb4-cfee-f918b94b68c9
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-eec68bcf-c387-73a4-474b-335f2a519cb8
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-05ef5dbb-3236-d20e-1c4a-0d49913f2063
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-8f1154a0-c66b-30f3-e1ad-6526256819ee
                host: u24
                memory:
                    total: "270068678656"
                os: Linux-6.14.0-32-generic-x86_64-with-glibc2.39
                program: /home/tahir/AAAI-26-INTENT/intent.py
                python: CPython 3.13.13
                root: /home/tahir/AAAI-26-INTENT
                startedAt: "2026-06-26T10:25:57.498560Z"
                writerId: qvb8z46cg7xsgo710fhvnw57dxy9ojn5
        m: []
        python_version: 3.13.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
            "3":
                - 1
                - 2
                - 13
                - 16
                - 61
            "4": 3.13.13
            "5": 0.26.0
            "6": 5.7.0
            "10":
                - 20
            "12": 0.26.0
            "13": linux-x86_64
adam_epsilon:
    value: 1e-08
biaffine_dim:
    value: 128
bislu_aux_loss_coef:
    value: 0.3
cache_dir:
    value: ""
dev_fraction:
    value: 0.1
dev_split:
    value: validation
do_eval:
    value: true
do_train:
    value: true
dropout_rate:
    value: 0.1
early_stopping:
    value: 5
ee_loss_coef:
    value: 0.3
ee_patience:
    value: 3
eval_batch_size:
    value: 8
freq_min_count:
    value: 1
freq_smoothing:
    value: 0.5
gpu:
    value: 1
gradient_accumulation_steps:
    value: 2
hf_dataset:
    value: chirunder/MixAtis_for_DecoderOnly
hidden_dim_ffw:
    value: 300
learning_rate:
    value: 2e-05
logging_steps:
    value: 200
loss_coef_intent:
    value: 0.5
loss_coef_intent_scl:
    value: 0.5
loss_coef_slot:
    value: 0.5
loss_coef_slot_scl:
    value: 0.5
max_grad_norm:
    value: 1
max_seq_length:
    value: 100
min_exit_layer:
    value: null
model_name_or_path:
    value: meta-llama/Llama-3.2-1B
num_train_epochs:
    value: 15
output_dir:
    value: ./out/atis_run1
sd_loss_coef:
    value: 0.5
tau_intent:
    value: 0.05
tau_slot:
    value: 0.1
test_fraction:
    value: 0.1
test_split:
    value: test
train_batch_size:
    value: 16
train_split:
    value: train
tuning_metric:
    value: mean_intent_slot
use_amp:
    value: true
use_freq_exit:
    value: true
use_gc:
    value: true
use_intent_context_attention:
    value: false
use_scl:
    value: false
use_sd:
    value: false
use_soft_slot:
    value: true
use_wandb:
    value: true
wandb_entity:
    value: null
wandb_project:
    value: bislu-pabee
wandb_run_name:
    value: llama1b_atis_tau0.05_p3
wandb_watch_freq:
    value: 100
warmup_proportion:
    value: 0.1
weight_decay:
    value: 0.01
